apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-config
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- .Values.config.application | toYaml | nindent 4 }}
