apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  azureOpenaiKey: {{ .Values.env.secret.AZURE_OPENAI_KEY | b64enc }}
  azureResourceName: {{ .Values.env.secret.AZURE_RESOURCE_NAME | b64enc }}