name: Publish package to GitHub Packages
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish package
        run: cd query_test_spec && ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.XNAT_JFROG_USER }}
          MAVEN_PASSWORD: ${{ secrets.XNAT_JFROG_TOKEN }}