name: Build and publish
on:
  push:
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Publish query_test_spec
        run: cd query_test_spec && ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.XNAT_JFROG_USER }}
          MAVEN_PASSWORD: ${{ secrets.XNAT_JFROG_TOKEN }}

      - name: Run tests
        run: ./gradlew test