name: Build and publish
on:
  push:
env:
  REGISTRY: ghcr.io
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          cache-disabled: true

      - name: Publish query_test_spec
        run: cd query_test_spec && ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.XNAT_JFROG_USER }}
          MAVEN_PASSWORD: ${{ secrets.XNAT_JFROG_TOKEN }}

      - name: Run tests
        run: ./gradlew test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ ENV.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ ENV.REGISTRY }}/washu-tag/data-generator:latest
          push: true